version: '3.9'

services:
  kali_terminal:
    build:
      context: ./kali_terminal
      dockerfile: Dockerfile 
    container_name: kali_terminal
    #restart: always
    ports:
      - 8888:8888
    networks:
      external_net:
        ipv4_address: 172.20.3.2

  ubuntu_admin:
    build:
      context: ./ubuntu_admin
      dockerfile: Dockerfile 
    container_name: ubuntu_admin
    #restart: always
    expose:
      - 161/udp
      - 22
    volumes:
      - ./ubuntu_vnc/coredump/:/var/lib/systemd/coredump/
      - ./ubuntu_vnc/Desktop/:/root/Desktop/
    networks:
      internal_net:
        ipv4_address: 10.10.3.2

  ftp_server:
    build:
      context: ./ftp_server
      dockerfile: Dockerfile
    container_name: ftp_server
    restart: always
    expose:
      - 20
      - 21
    networks:
      internal_net:
        ipv4_address: 10.10.3.4

  web_flask:
     build:
       context: ./web_flask
       dockerfile: Dockerfile
     container_name: web_flask
     volumes:
       - ./web_flask/app/todo_app/instance/:/app/instance/
     restart: always
     expose:
       - 80
       - 22
     networks:
       external_net:
         ipv4_address: 172.20.3.3
       internal_net:
         ipv4_address: 10.10.3.3


networks:
  external_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.3.0/24
          gateway: 172.20.3.1

  internal_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.3.0/24
          gateway: 10.10.3.1
